permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Deploy com CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name MeuApp \
            --deployment-group-name MeuGrupo \
            --s3-location bucket=my-bucket,key=app.zip,bundleType=zip


     ##       Essa abordagem exige configuração prévia no IAM e no CodeDeploy, mas é altamente segura e escalável.
